# Generated by Django 2.2.7 on 2020-01-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(default='  ', max_length=64)),
                ('phone', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='  ', max_length=300)),
            ],
        ),
    ]
