# Generated by Django 2.2.7 on 2020-01-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200101_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='  ', max_length=20),
        ),
    ]
