# Generated by Django 2.2.7 on 2020-02-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
