# Generated by Django 2.2.7 on 2020-02-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_delete_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('birthdate', models.DateField(max_length=8)),
                ('creditcardno', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
