# Generated by Django 3.0.3 on 2020-02-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200212_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
